/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Date;
import conexion.conexionSnayder;
import java.sql.Connection;
import java.sql.PreparedStatement;

import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

import javax.swing.JOptionPane;

public class principal extends javax.swing.JFrame {

    conexionSnayder con = new conexionSnayder();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;

    public principal() {
        initComponents();
        setLocationRelativeTo(null);
        H_listar_SnayderDelCarpio();

        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(200);
        nm.setMinimum(0);
        nm.setStepSize(2);
        botones.add(txt_Combo1_SnayderDelCarpio);
        botones.add(txt_Combo2_SnayderDelCarpio);
        botones.add(txt_Combo3_SnayderDelCarpio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Nombre_SnayderDelCarpio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Correo_SnayderDelCarpio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_telefono_SnayderDelCarpio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_TipoH_SnayderDelCarpio = new javax.swing.JComboBox<>();
        txt_HabitacionesSpinner_SnayderDelCarpio = new javax.swing.JSpinner();
        txt_SpinnerH_Mostrar_SnayderDelCarpio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Personas_SnayderDelCarpio = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txt_Peticion_SnayderDelCarpio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Combo1_SnayderDelCarpio = new javax.swing.JRadioButton();
        txt_Combo2_SnayderDelCarpio = new javax.swing.JRadioButton();
        txt_Combo3_SnayderDelCarpio = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txt_ID_SnayderDelCarpio = new javax.swing.JTextField();
        txt_SpinnerPersonasMostrar_SnayderDelCarpio = new javax.swing.JTextField();
        txt_FechaE_SnayderDelCarpio = new com.toedter.calendar.JDateChooser();
        txt_FechaS_SnayderDelCarpio = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_Agregar_SnayderDelCarpio = new javax.swing.JButton();
        btn_Eliminar_SnayderDelCarpio = new javax.swing.JButton();
        btn_Actualizar_SnayderDelCarpio = new javax.swing.JButton();
        btn_Nuevo_SnayderDelCarpio = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("FORMATO DE LOS DATOS"));

        jLabel1.setText("Nombre Completo:");

        txt_Nombre_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_SnayderDelCarpioActionPerformed(evt);
            }
        });

        jLabel2.setText("Correo Electronico:");

        jLabel3.setText("Teléfono:");

        jLabel4.setText("Fecha de Entrada:");

        jLabel5.setText("Fecha de Salida:");

        jLabel6.setText("Número de Habitaciones");

        jLabel7.setText("Tipo de Habitación:");

        txt_TipoH_SnayderDelCarpio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Familiar", "Matrimonial" }));

        txt_HabitacionesSpinner_SnayderDelCarpio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_HabitacionesSpinner_SnayderDelCarpioStateChanged(evt);
            }
        });

        txt_SpinnerH_Mostrar_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SpinnerH_Mostrar_SnayderDelCarpioActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero de personas");

        txt_Personas_SnayderDelCarpio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_Personas_SnayderDelCarpioStateChanged(evt);
            }
        });

        jLabel9.setText("Peticiones Especiales");

        txt_Peticion_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Peticion_SnayderDelCarpioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Metodo de pago:");

        txt_Combo1_SnayderDelCarpio.setText("Tarjeta de crédito");

        txt_Combo2_SnayderDelCarpio.setText("Yape");

        txt_Combo3_SnayderDelCarpio.setText("Efectivo");

        jLabel11.setText("ID");

        txt_ID_SnayderDelCarpio.setEditable(false);

        txt_FechaE_SnayderDelCarpio.setDateFormatString("yyyy-MM-dd");

        txt_FechaS_SnayderDelCarpio.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_ID_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_FechaE_SnayderDelCarpio, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txt_FechaS_SnayderDelCarpio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_TipoH_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Combo2_SnayderDelCarpio)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(txt_Combo3_SnayderDelCarpio)
                                        .addGap(52, 52, 52)
                                        .addComponent(txt_Combo1_SnayderDelCarpio))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_Peticion_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_HabitacionesSpinner_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(30, 30, 30)
                                            .addComponent(txt_Personas_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_SpinnerH_Mostrar_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(139, 139, 139))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefono_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Correo_SnayderDelCarpio, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txt_Nombre_SnayderDelCarpio))
                                .addGap(162, 162, 162)
                                .addComponent(txt_SpinnerPersonasMostrar_SnayderDelCarpio)))
                        .addGap(231, 231, 231))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_HabitacionesSpinner_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_ID_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Nombre_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_SpinnerH_Mostrar_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Personas_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Correo_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SpinnerPersonasMostrar_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_telefono_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_FechaE_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_FechaS_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_TipoH_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Peticion_SnayderDelCarpio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Combo1_SnayderDelCarpio)
                            .addComponent(txt_Combo2_SnayderDelCarpio)
                            .addComponent(txt_Combo3_SnayderDelCarpio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TABLA DE DATOS"));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CORREO", "TELEFONO", "FECHA_ENTRADA", "FECHA_SALIDA", "TIPO_HABITACION", "NUMERO_HABITACION", "NUMERO_PERSONAS", "PETICIONES", "METODO_PAGO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);
        if (TablaDatos.getColumnModel().getColumnCount() > 0) {
            TablaDatos.getColumnModel().getColumn(0).setMinWidth(28);
            TablaDatos.getColumnModel().getColumn(0).setPreferredWidth(28);
            TablaDatos.getColumnModel().getColumn(0).setMaxWidth(28);
            TablaDatos.getColumnModel().getColumn(1).setMinWidth(150);
            TablaDatos.getColumnModel().getColumn(1).setPreferredWidth(150);
            TablaDatos.getColumnModel().getColumn(1).setMaxWidth(150);
            TablaDatos.getColumnModel().getColumn(3).setMinWidth(80);
            TablaDatos.getColumnModel().getColumn(3).setPreferredWidth(80);
            TablaDatos.getColumnModel().getColumn(3).setMaxWidth(80);
            TablaDatos.getColumnModel().getColumn(4).setMinWidth(100);
            TablaDatos.getColumnModel().getColumn(4).setPreferredWidth(100);
            TablaDatos.getColumnModel().getColumn(4).setMaxWidth(100);
            TablaDatos.getColumnModel().getColumn(5).setMinWidth(100);
            TablaDatos.getColumnModel().getColumn(5).setPreferredWidth(100);
            TablaDatos.getColumnModel().getColumn(5).setMaxWidth(100);
            TablaDatos.getColumnModel().getColumn(6).setMinWidth(180);
            TablaDatos.getColumnModel().getColumn(6).setPreferredWidth(180);
            TablaDatos.getColumnModel().getColumn(6).setMaxWidth(180);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BOTONES DE COMANDO"));

        btn_Agregar_SnayderDelCarpio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Agregar_SnayderDelCarpio.setText("Agregar");
        btn_Agregar_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_SnayderDelCarpioActionPerformed(evt);
            }
        });

        btn_Eliminar_SnayderDelCarpio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Eliminar_SnayderDelCarpio.setText("Eliminar");
        btn_Eliminar_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_SnayderDelCarpioActionPerformed(evt);
            }
        });

        btn_Actualizar_SnayderDelCarpio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Actualizar_SnayderDelCarpio.setText("Actualizar");
        btn_Actualizar_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Actualizar_SnayderDelCarpioActionPerformed(evt);
            }
        });

        btn_Nuevo_SnayderDelCarpio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Nuevo_SnayderDelCarpio.setText("Nuevo");
        btn_Nuevo_SnayderDelCarpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Nuevo_SnayderDelCarpioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Actualizar_SnayderDelCarpio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Agregar_SnayderDelCarpio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Eliminar_SnayderDelCarpio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Nuevo_SnayderDelCarpio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btn_Agregar_SnayderDelCarpio)
                .addGap(63, 63, 63)
                .addComponent(btn_Actualizar_SnayderDelCarpio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btn_Nuevo_SnayderDelCarpio)
                .addGap(74, 74, 74)
                .addComponent(btn_Eliminar_SnayderDelCarpio)
                .addGap(43, 43, 43))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("05_SnayderDelCarpio_Crud_HotelVillaDelSur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("FORMATO DE LOS DATOS");
        jPanel2.getAccessibleContext().setAccessibleName("TABLA DE DATOS");
        jPanel3.getAccessibleContext().setAccessibleName("BOTONES DE COMANDOS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SpinnerH_Mostrar_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SpinnerH_Mostrar_SnayderDelCarpioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SpinnerH_Mostrar_SnayderDelCarpioActionPerformed

    private void txt_Peticion_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Peticion_SnayderDelCarpioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Peticion_SnayderDelCarpioActionPerformed

    private void btn_Nuevo_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Nuevo_SnayderDelCarpioActionPerformed
        H_Nuevo_SnayderDelCarpio();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Nuevo_SnayderDelCarpioActionPerformed

    private void txt_Nombre_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_SnayderDelCarpioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre_SnayderDelCarpioActionPerformed

    private void btn_Agregar_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_SnayderDelCarpioActionPerformed
        H_Agregar_SnayderDelCarpio();
        H_listar_SnayderDelCarpio();
        H_Nuevo_SnayderDelCarpio(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_Agregar_SnayderDelCarpioActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        int fila = TablaDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar datos");
        } else {
            id = Integer.parseInt((String) TablaDatos.getValueAt(fila, 0).toString());
            String nombre = (String) TablaDatos.getValueAt(fila, 1);
            String email = (String) TablaDatos.getValueAt(fila, 2);
            String telefono = (String) TablaDatos.getValueAt(fila, 3);
            String fechaE = (String) TablaDatos.getValueAt(fila, 4).toString();
            String fechaS = (String) TablaDatos.getValueAt(fila, 5).toString();
            String tipoH = (String) TablaDatos.getValueAt(fila, 6);
            String numeroH = (String) TablaDatos.getValueAt(fila, 7);
            String numeroP = (String) TablaDatos.getValueAt(fila, 8);
            String peticiones = (String) TablaDatos.getValueAt(fila, 9);
            String metodoP = (String) TablaDatos.getValueAt(fila, 10);

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Ajusta el formato a tus necesidades

            try {
                Date dateE = dateFormat.parse(fechaE);
                Date dateS = dateFormat.parse(fechaS);
                txt_FechaE_SnayderDelCarpio.setDate(dateE);
                txt_FechaS_SnayderDelCarpio.setDate(dateS);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Error al convertir las fechas");
            }

            txt_ID_SnayderDelCarpio.setText("" + id);
            txt_Nombre_SnayderDelCarpio.setText(nombre);
            txt_Correo_SnayderDelCarpio.setText(email);
            txt_telefono_SnayderDelCarpio.setText(telefono);
            txt_TipoH_SnayderDelCarpio.setSelectedItem(tipoH);
            txt_SpinnerH_Mostrar_SnayderDelCarpio.setText(numeroH);
            txt_SpinnerPersonasMostrar_SnayderDelCarpio.setText(numeroP);
            txt_Peticion_SnayderDelCarpio.setText(peticiones);
            if (metodoP.equals(txt_Combo1_SnayderDelCarpio.getText())) {
                txt_Combo1_SnayderDelCarpio.setSelected(true);
            } else if (metodoP.equals(txt_Combo2_SnayderDelCarpio.getText())) {
                txt_Combo2_SnayderDelCarpio.setSelected(true);
            } else if (metodoP.equals(txt_Combo3_SnayderDelCarpio.getText())) {
                txt_Combo3_SnayderDelCarpio.setSelected(true);
            }
        }

    }//GEN-LAST:event_TablaDatosMouseClicked

    private void txt_HabitacionesSpinner_SnayderDelCarpioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_HabitacionesSpinner_SnayderDelCarpioStateChanged
        txt_SpinnerH_Mostrar_SnayderDelCarpio.setText("Número de Habitaciones : " + txt_HabitacionesSpinner_SnayderDelCarpio.getValue().toString());
    }//GEN-LAST:event_txt_HabitacionesSpinner_SnayderDelCarpioStateChanged

    private void txt_Personas_SnayderDelCarpioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_Personas_SnayderDelCarpioStateChanged
        txt_SpinnerPersonasMostrar_SnayderDelCarpio.setText("Numero de personas : " + txt_Personas_SnayderDelCarpio.getValue().toString());
    }//GEN-LAST:event_txt_Personas_SnayderDelCarpioStateChanged

    private void btn_Eliminar_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_SnayderDelCarpioActionPerformed
        H_Eliminar_SnayderDelCarpio();
        H_listar_SnayderDelCarpio();
        H_Nuevo_SnayderDelCarpio(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_Eliminar_SnayderDelCarpioActionPerformed

    private void btn_Actualizar_SnayderDelCarpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Actualizar_SnayderDelCarpioActionPerformed
        H_Modificar_SnayderDelCarpio();
        H_listar_SnayderDelCarpio();
        H_Nuevo_SnayderDelCarpio();
    }//GEN-LAST:event_btn_Actualizar_SnayderDelCarpioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    void H_listar_SnayderDelCarpio() {
       String sql = "select * from personas";
        //String sql = "select * from personas WHERE estado = 'A'";
        try {
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);

            DefaultTableModel modelo = (DefaultTableModel) TablaDatos.getModel();

            // Limpiar la tabla antes de agregar nuevos datos
            modelo.setRowCount(0);
            while (rs.next()) {
                Object[] persona = new Object[13];
                persona[0] = rs.getInt("id");
                persona[1] = rs.getString("nombre_completo");
                persona[2] = rs.getString("email");
                persona[3] = rs.getString("telefono");
                persona[4] = rs.getDate("fechaE");
                persona[5] = rs.getDate("fechaS");
                persona[6] = rs.getString("tipo_de_habitacion");
                persona[7] = rs.getString("numero_de_habitacion");
                persona[8] = rs.getString("numero_de_personas");
                persona[9] = rs.getString("peticiones_especiales");
                persona[10] = rs.getString("metodo_de_pago");
                                persona[11] = rs.getString("estado");

                modelo.addRow(persona);
            }
            TablaDatos.setModel(modelo);
        } catch (Exception e) {
            System.out.println("Error listart" + e);
        }
    }

    void H_Agregar_SnayderDelCarpio() {
        String nombre = txt_Nombre_SnayderDelCarpio.getText();
        String email = txt_Correo_SnayderDelCarpio.getText();
        String telefono = txt_telefono_SnayderDelCarpio.getText();
        java.util.Date fechaE = txt_FechaE_SnayderDelCarpio.getDate(); // Util Date
        java.util.Date fechaS = txt_FechaS_SnayderDelCarpio.getDate(); // Util Date
        if (fechaE == null || fechaS == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar las fechas de entrada y salida.");
            return;
        }
        java.sql.Date sqlFechaE = new java.sql.Date(fechaE.getTime()); // SQL Date
        java.sql.Date sqlFechaS = new java.sql.Date(fechaS.getTime()); // SQL Date
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String fechaEString = dateFormat.format(fechaE);
        String fechaSString = dateFormat.format(fechaS);
        String tipoH = (String) txt_TipoH_SnayderDelCarpio.getSelectedItem();
        String numeroH = txt_SpinnerH_Mostrar_SnayderDelCarpio.getText();
        String numeroP = txt_SpinnerPersonasMostrar_SnayderDelCarpio.getText();
        String peticiones = txt_Peticion_SnayderDelCarpio.getText();
        String metodoP = "";
        if (txt_Combo1_SnayderDelCarpio.isSelected()) {
            metodoP = txt_Combo1_SnayderDelCarpio.getText();
        } else if (txt_Combo2_SnayderDelCarpio.isSelected()) {
            metodoP = txt_Combo2_SnayderDelCarpio.getText();
        } else if (txt_Combo3_SnayderDelCarpio.isSelected()) {
            metodoP = txt_Combo3_SnayderDelCarpio.getText();
        }
        if (nombre.equals("") || email.equals("")) {
            JOptionPane.showMessageDialog(null, "no hay datos por agregar");
        } else {
            String sql = "INSERT INTO personas (nombre_completo, email, telefono, fechaE, fechaS, tipo_de_habitacion, numero_de_habitacion, numero_de_personas, peticiones_especiales, metodo_de_pago) "
                    + "VALUES ('" + nombre + "', '" + email + "', '" + telefono + "', '" + sqlFechaE + "', '" + sqlFechaS + "', '" + tipoH + "', '" + numeroH + "', '" + numeroP + "', '" + peticiones + "', '" + metodoP + "')";
            try {
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Registro de la persona Agregada");
                H_limpiartabla_SnayderDelCarpio();
            } catch (Exception e) {
                System.out.println("Error Agregar" + e);
            }
        }
    }

void H_limpiartabla_SnayderDelCarpio() {
    DefaultTableModel modelo = (DefaultTableModel) TablaDatos.getModel();
    // Verificar si el modelo es nulo antes de intentar limpiar la tabla
    if (modelo != null) {
        // Usar un bucle inverso para eliminar las filas
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    } else {
        System.out.println("El modelo de la tabla es nulo. No se puede limpiar la tabla.");
    }
}


    void H_Eliminar_SnayderDelCarpio() {
        int fila = TablaDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar datos");
        } else {
            int id = Integer.parseInt(TablaDatos.getValueAt(fila, 0).toString());
            String sql = "UPDATE personas SET estado = 'R' WHERE id = ?";
            try {
                cn = con.getConnection();
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setInt(1, id);
                int resultado = pst.executeUpdate();
                if (resultado > 0) {
                    JOptionPane.showMessageDialog(null, "Registro marcado como eliminado lógicamente");
                    H_limpiartabla_SnayderDelCarpio();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo marcar como eliminado lógicamente");
                }
            } catch (SQLException e) {
                System.out.println("Error al eliminar lógicamente: " + e.getMessage());
            }
        }
    }

    void H_Nuevo_SnayderDelCarpio() {
        txt_ID_SnayderDelCarpio.setText("");
        txt_Nombre_SnayderDelCarpio.setText("");
        txt_Correo_SnayderDelCarpio.setText("");
        txt_telefono_SnayderDelCarpio.setText("");
        txt_FechaE_SnayderDelCarpio.setDate(null);
        txt_FechaS_SnayderDelCarpio.setDate(null);
        txt_TipoH_SnayderDelCarpio.setSelectedItem(null);
        txt_SpinnerH_Mostrar_SnayderDelCarpio.setText("");
        txt_SpinnerPersonasMostrar_SnayderDelCarpio.setText("");
        txt_Peticion_SnayderDelCarpio.setText("");
        botones.clearSelection();
        txt_HabitacionesSpinner_SnayderDelCarpio.setValue(0);
        txt_Personas_SnayderDelCarpio.setValue(0);
    }

    void H_Modificar_SnayderDelCarpio() {
        String nombre = txt_Nombre_SnayderDelCarpio.getText();
        String email = txt_Correo_SnayderDelCarpio.getText();
        String telefono = txt_telefono_SnayderDelCarpio.getText();
        java.util.Date fechaE = txt_FechaE_SnayderDelCarpio.getDate(); // Util Date
        java.util.Date fechaS = txt_FechaS_SnayderDelCarpio.getDate(); // Util Date
        if (fechaE == null || fechaS == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar las fechas de entrada y salida.");
            return;
        }
        java.sql.Date sqlFechaE = new java.sql.Date(fechaE.getTime()); // SQL Date
        java.sql.Date sqlFechaS = new java.sql.Date(fechaS.getTime()); // SQL Date
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String fechaEString = dateFormat.format(fechaE);
        String fechaSString = dateFormat.format(fechaS);
        String tipoH = (String) txt_TipoH_SnayderDelCarpio.getSelectedItem();
        String numeroH = txt_SpinnerH_Mostrar_SnayderDelCarpio.getText();
        String numeroP = txt_SpinnerPersonasMostrar_SnayderDelCarpio.getText();
        String peticiones = txt_Peticion_SnayderDelCarpio.getText();
        String metodoP = "";
        if (txt_Combo1_SnayderDelCarpio.isSelected()) {
            metodoP = txt_Combo1_SnayderDelCarpio.getText();
        } else if (txt_Combo2_SnayderDelCarpio.isSelected()) {
            metodoP = txt_Combo2_SnayderDelCarpio.getText();
        } else if (txt_Combo3_SnayderDelCarpio.isSelected()) {
            metodoP = txt_Combo3_SnayderDelCarpio.getText();
        }
        String sql = "UPDATE personas SET nombre_completo = '" + nombre + "', email = '" + email + "', telefono = '" + telefono + "', fechaE = '" + sqlFechaE + "', fechaS = '" + sqlFechaS + "', tipo_de_habitacion = '" + tipoH + "', numero_de_habitacion = '" + numeroH + "', numero_de_personas = '" + numeroP + "', peticiones_especiales = '" + peticiones + "', metodo_de_pago = '" + metodoP + "' WHERE id =" + id;

        if (nombre.equals("") || email.equals("")) {
            JOptionPane.showMessageDialog(null, "no hay datos por agregar");
        } else {
            try {
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "registro actualizado");
                H_limpiartabla_SnayderDelCarpio();
            } catch (Exception e) {
                System.out.println("Error Modificar" + e);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton btn_Actualizar_SnayderDelCarpio;
    private javax.swing.JButton btn_Agregar_SnayderDelCarpio;
    private javax.swing.JButton btn_Eliminar_SnayderDelCarpio;
    private javax.swing.JButton btn_Nuevo_SnayderDelCarpio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton txt_Combo1_SnayderDelCarpio;
    private javax.swing.JRadioButton txt_Combo2_SnayderDelCarpio;
    private javax.swing.JRadioButton txt_Combo3_SnayderDelCarpio;
    private javax.swing.JTextField txt_Correo_SnayderDelCarpio;
    private com.toedter.calendar.JDateChooser txt_FechaE_SnayderDelCarpio;
    private com.toedter.calendar.JDateChooser txt_FechaS_SnayderDelCarpio;
    private javax.swing.JSpinner txt_HabitacionesSpinner_SnayderDelCarpio;
    private javax.swing.JTextField txt_ID_SnayderDelCarpio;
    private javax.swing.JTextField txt_Nombre_SnayderDelCarpio;
    private javax.swing.JSpinner txt_Personas_SnayderDelCarpio;
    private javax.swing.JTextField txt_Peticion_SnayderDelCarpio;
    private javax.swing.JTextField txt_SpinnerH_Mostrar_SnayderDelCarpio;
    private javax.swing.JTextField txt_SpinnerPersonasMostrar_SnayderDelCarpio;
    private javax.swing.JComboBox<String> txt_TipoH_SnayderDelCarpio;
    private javax.swing.JTextField txt_telefono_SnayderDelCarpio;
    // End of variables declaration//GEN-END:variables
}
